#!/bin/bash
set -e

if [ "$BUNDLE_GEMFILE" == "" ]; then
  BUNDLE_GEMFILE="$(cd "$(dirname "$0")" && pwd)/Gemfile"
  export BUNDLE_GEMFILE
  bundle install --jobs=3 --retry=3 --path="${BUNDLE_PATH:-vendor/bundle}"
fi

ERRORS=0

if [ -d nubis/puppet ]; then
  echo "Running Puppet Lint"
  bundle exec puppet-lint --no-puppet_url_without_modules-check --no-80chars-check --no-140chars-check --fail-on-warnings nubis/puppet/*pp || ERRORS=$(( ERRORS + 1 ))
fi

echo "Running ShellCheck"
find -path "./.git*" -prune -o -path ./nubis/travis -prune -o -path ./nubis/librarian-puppet -prune -o -path ./nubis/.tmp -prune -o -type f -a \! -name '*.tmpl' -print0 | xargs -0 file | grep 'shell script' | cut -d: -f1 | xargs -r shellcheck || ERRORS=$(( ERRORS + 1 ))

echo "Running JSON Lint"
find  -not \( \( -path ./nubis/librarian-puppet -o -path ./nubis/.tmp -o -path ./nubis/travis \)  -prune \) -type f -name '*.json*' -print0 | xargs -r0 bundle exec jsonlint || ERRORS=$(( ERRORS + 1 ))

echo "Running MarkDown Lint"
find  -not \( \( -path ./nubis/librarian-puppet -o -path ./nubis/.tmp -o -path ./nubis/travis \)  -prune \) -type f -name \*.md  | grep -v ./CHANGELOG.md | xargs -r bundle exec mdl --style ${PWD}/nubis/travis/style.rb || ERRORS=$(( ERRORS + 1 ))

if [ -f "nubis/Puppetfile" ]; then
  echo "Installing specified puppet modules"
  ( cd nubis && bundle exec librarian-puppet install )
  echo "Checking for outdated puppet modules"
  ( cd nubis && bundle exec librarian-puppet outdated )
fi

exit $ERRORS
