#!/bin/bash
set -e

PACKER_VERSION="1.1.2"
NUBIS_BUILDER_VERSION="v1.5.6"

if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
  echo "AMI building not supported (yet) on Pull-Requests"
  exit 0
fi

if [ -z "$AWS_ACCESS_KEY_ID" ] || [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
  echo "Please set AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY"
  exit 1
fi

if [ "$BUNDLE_GEMFILE" == "" ]; then
  BUNDLE_GEMFILE="$(cd "$(dirname "$0")" && pwd)/Gemfile"
  export BUNDLE_GEMFILE
  bundle install --jobs=3 --retry=3 --path="${BUNDLE_PATH:-vendor/bundle}"
fi

export PATH=$PATH:$HOME/.local/bin:$HOME/bin/nubis-builder/bin

if [ "$(packer --version 2>/dev/null)" != "$PACKER_VERSION" ]; then
  wget -O /tmp/packer.zip "https://releases.hashicorp.com/packer/$PACKER_VERSION/packer_${PACKER_VERSION}_linux_amd64.zip"
  ( cd "$HOME/bin" && unzip /tmp/packer.zip )
fi

if [ ! -d "$HOME/bin/nubis-builder/.git" ]; then
  rm -rfv "$HOME/bin/nubis-builder"
  git clone https://github.com/nubisproject/nubis-builder.git "$HOME/bin/nubis-builder"
fi

if [ "$(git -C "$HOME/bin/nubis-builder" describe)" != "$NUBIS_BUILDER_VERSION" ]; then
  git -C "$HOME/bin/nubis-builder" pull origin master
  git -C "$HOME/bin/nubis-builder" fetch --tags
  git -C "$HOME/bin/nubis-builder" checkout "$NUBIS_BUILDER_VERSION"
fi

cat <<EOF > "$HOME/bin/nubis-builder/secrets/variables.json"
{
  "variables": {
    "aws_region": "${AWS_REGION:-us-west-2}",
    "ami_regions": "ap-northeast-1,ap-northeast-2,ap-southeast-1,ap-southeast-2,eu-central-1,eu-west-1,sa-east-1,us-east-1,us-west-1,us-west-2"
  }
}
EOF

aws --version
packer version
nubis-builder --version


#Kick the build
bundle exec nubis-builder build --instance-type c3.large --spot &

minutes=0
limit=60

# Generate invisible output every minute to keep Travis from killing up
while kill -0 $! >/dev/null 2>&1; do
  echo -n -e " \b" # never leave evidences!

  if [ $minutes == $limit ]; then
    break;
  fi

  minutes=$((minutes+1))

  sleep 60
done


exit 0
